### PR TITLE
Update list.md

### PR DESCRIPTION
**Pull request by Global-System-Indonesia**
Toko Emas Berlian Harisa, aims to make it easier for pioneers in the world, especially Indonesia, in buying and selling gold and diamonds.
https://harisajewellery.com

### CODE REVIEW

**Comment by CryptoGing** [comment]
@Global-System-Indonesia Are you going to open source your apps code base? Once you confirm this then I will be able to get everything set up

**Comment by Global-System-Indonesia** [comment]
Yes

**Review by CryptoGing — APPROVED** [review]

**Comment by CryptoGing** [comment]
Please add you code to this repository and update the license.md file with the relevant information

**Comment by CryptoGing** [comment]
https://github.com/pi-apps/toko-emas-berlian-harisa

**Pull request merged**
