### PR TITLE
add News for Pi to PiOS

### PR DESCRIPTION
**Pull request by JustinLi97**

### CODE REVIEW

**Review by kokkalis — CHANGES_REQUESTED** [review]
Great project idea,  but is it possible to call it "News on Pi" or another name, to avoid confusion with apps developed by the Pi Core Team?

**Comment by JustinLi97** [comment]
> Great project idea, but is it possible to call it "News on Pi" or another name, to avoid confusion with apps developed by the Pi Core Team?

Ok, I am willing to modify it to  "News for Pi"

**Comment by a38202839** [comment]
你好博士，关于火必交易所上的PI是怎么回事，还有PI的KYC什么时候能全面开放

**Comment by a38202839** [comment]
PIOS是移动端操作系统还是PC端

**Review by kokkalis — APPROVED** [review]

**Pull request merged**
