### PR TITLE
add piiq.network project

### PR DESCRIPTION
**Pull request by jiakuant1120**
Let's Keep Building

### CODE REVIEW

**Review by kokkalis — COMMENTED** [review]
Do you intend to license the code under PiOS or are you just requesting to list this here for visibility? Just making sure we understand the context. (Note this list is for PiOS-licensed apps)

Also, do you mind using a name that does not start with Pi, to avoid confusion with apps developed by the Pi Core Team.
Good examples could be "Door to Pi", Door for Pi", or "Door"

**Comment by jiakuant1120** [comment]
> 
Yes, I intend to license the code under PiOS. The project aims to contribute to the pi community.
The project names Door, just because the four letters 'piiq' in domain piiq.network like the door.
The name ‘Door for Pi’ is great. 
Do I need to resubmit?

**Review by kokkalis — APPROVED** [review]

**Comment by Zws758857** [comment]
>pi@Zws758857


> I plan to download the license code in PiOS, I am Ganzhou City, Jiangxi Province, China Guo Hong Pai (my "Guo Hong Pai" trademark logo is: GHP) computer service studio enterprise, please Mr. Kokkalis approval, salute!

**Comment by Zws758857** [comment]
我计划在PiOS下载许可证代码，我是中国江西省赣州市Guohong School（我的“Guohong School”商标标识是：GHP）电脑服务工作室企业，请kokkalis先生批准，致敬！

**Review by Zws758857 — COMMENTED** [review]
> 我计划在PiOS中下载许可证代码，我是江西省赣州市宁都县会同乡国宏派电脑服务工作室企业，国宏派的商标标识是GHP，请Kokkalis先生批准，致敬！

**Comment by Zws758857** [comment]
> 我计划在PiOS中下载许可证代码，我是江西省赣州市宁都县会同乡国宏派电脑服务工作室企业，国宏派的商标标识是GHP，请Kokkalis先生批准，致敬！

**Comment by Zws758857** [comment]
> 我在PiOS中下载许可证代码，我是江西省赣州市宁都县会同乡国宏派电脑服务工作室企业，国宏派的商标标识是GHP，请Kokkalis先生批准，致敬！

微信图片_20241116194326

> pi@Zws758857

> 

>

**Pull request merged**
