### PR TITLE
Update list.md

### PR DESCRIPTION
**Pull request by bharatshoppingmart**
added to the list our project - Bharat Shopping Mart (e-commerce app)- India's cutting-edge e-commerce platform, revolutionizing transactions with Pi™ cryptocurrency for a secure, diverse, and user-friendly shopping experience, fostering economic growth.

### CODE REVIEW

**Comment by CryptoGing** [comment]
This list is for projects that going to open source their code, are you willing to do that?

**Comment by bharatshoppingmart** [comment]
No we not going to open source code of our project, we thought it's the
list of project that can be presented in brainstorm, that's what moderator
suggested in chat,


We can't able to find publish button in brainstorm for our project to be
visible by all, we raised concerns many times, one of mod suggest this link
and add our project to lost, that's the reason we added



But we developing our app from scratch, so we don't going to open source
out code,

Kindly help us publish our project I'm brainstorm, it would be much helpful



Thanks and Regards,
Veeresh P
Bharat shopping mart

**Comment by CryptoGing** [comment]
I will close this PR out then since you don't want to open source your code. 

In terms of getting the project listed in Brainstorm our team is working on making some updates to the app that once completed should get your project reviewed by pioneers. Once reviewed and voted on then it will become listed if enough pioneers vote "yes".

**Comment by bharatshoppingmart** [comment]
Ok Thanks for the update, much appreciated


Regards
Bharat Shopping Mart

**Pull request closed without merging**
