### PR TITLE
Update list.md

### PR DESCRIPTION
**Pull request by pibartermall**
Pi Barter mall to PiOS

### CODE REVIEW

**Comment by pibartermall** [comment]
> Two questions:
> 
> 1. The name of the app can be in the form of “Barter Mall for Pi”, “Barter Mall on Pi”, “Barter Mall”, but not in the form of “Pi Barter Mall” to avoid confusion with apps developed by the Pi Core Team. Is it ok to make this change?
> 2. This is the list of PiOS-licensed apps. Do you intend to license the code as PiOS?
> 
> Thanks
**HI Thanks for the reminder and guidance, the new name has been changed to Barter Mall for Pi and we intend to license the code as PiOS Thanks** @kokkalis

**Comment by CryptoGing** [comment]
The repository has been created

**Comment by CryptoGing** [comment]
Please accept Nicolas changes and then merge the PR and your app will be added to the list.

**Review by pibartermall — COMMENTED** [review]
| Barter Mall for Pi| A large-scale online shopping mall, pioneers use PI coins to purchase goods or services, with more than 1 million registered users, and won the PI NETWORK Hackathon Honor Award | Consumer Utility | Node.js,Vue3, Html,Javascript, Mysql | [bartermall-for-pi](https://github.com/pi-apps/bartermall-for-pi) | pi://brainstorm.pi/project/60de794d35accf62f3ce4b7e | [https://www.lgkm.net](https://www.lgkm.net/) | (https://www.lgkm.net/) | https://www.lgkm.net |

**Review by pibbschat — APPROVED** [review]

**Review by pibbschat — APPROVED** [review]

**Review by pibbschat — APPROVED** [review]

**Review by pibbschat — APPROVED** [review]

**Review by pibartermall — COMMENTED** [review]
yes

**Pull request merged**
