### PR TITLE
GeraiPi Indonesia

### PR DESCRIPTION
**Pull request by roniahmadi**
my project using python , and using framework django 

Testnet Link = https://testnet.geraipi.id/

### CODE REVIEW

**Comment by Bayuda** [comment]
👍 Keep Spirit GeraiPi...💪

**Comment by RamadanHash** [comment]
👍

**Review by vinhhp1987 — APPROVED** [review]

**Comment by roniahmadi** [comment]
> I tried visiting your testnet app today and I couldn't advance past the loading page. Are you still developing the app?

This is final develop

**Comment by CryptoGing** [comment]
I was able to open and review the applications

Are you intending to open source your applications code?

**Comment by roniahmadi** [comment]
> I was able to open and review the applications
> 
> Are you intending to open source your applications code?

yeah , I have changed the visibility of github to public

**Review by CryptoGing — APPROVED** [review]

**Comment by CryptoGing** [comment]
@roniahmadi here is a repo for the code to be moved into. Please update the license.md file when you get chance. Thanks for your contribution. https://github.com/pi-apps/geraipi

**Pull request merged**
