### PR TITLE
Add Polls for Pi

### PR DESCRIPTION
**Pull request by eastmaels**

### CODE REVIEW

**Comment by CryptoGing** [comment]
Hello thank you for your interest in joining PiOS. This list is for applications that will be open source, do you intend to make the app code Open Source?

**Comment by CryptoGing** [comment]
Is the application that you are building a feature that developers can plug into their code base to create the polls or is it a stand alone application?

**Comment by eastmaels** [comment]
> Hello thank you for your interest in joining PiOS. This list is for applications that will be open source, do you intend to make the app code Open Source?

Yes I plan to make the code open source once repo is available here in pi-apps.

**Comment by CryptoGing** [comment]
I have created the Repo and added you as an Admin. You need to update the license text and add your application to this repository.

**Pull request merged**
