### PR TITLE
Apply ExplorePi with PiOS

### PR DESCRIPTION
**Pull request by 0205miss**

### CODE REVIEW

**Review by kokkalis — CHANGES_REQUESTED** [review]
Hi there, this project sounds like a good idea, but binding a user's public_key with pi_username may be a privacy concern for some Pioneers. Other than this feature, will the app provide something else? 

Or would it be more appropriate to send PR to the Pi Blockexplorer? https://github.com/pi-apps/pi-explorer

**Comment by 0205miss** [comment]
The explorer will have more statistic for blockchain.
Including ledger time,claim account,active account,etc.
Binding username with pi_blockchain account will be private and not necessary as default.
Also User can choose to be share his public_key by username or not. 
Seems pi explorer is fork from chatch, but there has some issue that isn't support in current stellar-core version.
The project is pioneer-based and easy to read/understand.
Such as claimable _balance we will let user easily see the date and the status

**Comment by siphuvn** [comment]
Thank you Dr. Kokkalis! We waiting for this moment.

**Review by kokkalis — COMMENTED** [review]
ok, great. Based on your comment I updated the description. What do you think?
Also, how about accusing the project ExplorePi instead of ExplorerPi? Just a suggestion, it is your choice. Let me know and I can merge the PR.

**Comment by 0205miss** [comment]
@kokkalis that sounds great, I just change it. The description is more suitable now tks.

**Comment by Altafkiani** [comment]
Be happy all

**Review by kokkalis — APPROVED** [review]

**Pull request merged**
