### PR TITLE
added Tippy in PiOS list

### PR DESCRIPTION
**Pull request by devnamrits**
Hi @CryptoGing I've raised PR for adding my app in PiOS list.

However, I'm unable to create brainstorm link through Pi Browser hence, I've not added it in this PR.

### CODE REVIEW

**Comment by CryptoGing** [comment]
Hello, Thanks for registering your intent to join PiOS. Just to confirm this list is for applications that are open source, do you intend to Open source your application code?

Second, I got your message in discord and have responded. Lets trouble shoot brainstorm from discord.

**Comment by devnamrits** [comment]
Yes, we ok with keeping our application code open source.

**Comment by devnamrits** [comment]
@CryptoGing 
Thank you I was able to create a proposal. I have added the proposal link. Please review.

**Review by pi-core-team — APPROVED** [review]

**Comment by pi-core-team** [comment]
@devnamrits I have created the repo and added you as an admin. You are all set to add your code, please make sure to update the license text in the repo

**Pull request merged**
