### PR TITLE
Update list.md: Adding  Pi Showroom Indonesia to the PiOS list

### PR DESCRIPTION
**Pull request by Pisshowroom**

### CODE REVIEW

**Comment by medomohamed22** [comment]
There is a problem with the browser application in the wallet. The QR code does not work correctly

**Comment by Pisshowroom** [comment]
Could you please clarify what you meant by "The QR code does not work correctly" @medomohamed22 ? Thank you.

**Review by KOSASIH — APPROVED** [review]

**Review by KOSASIH — CHANGES_REQUESTED** [review]
More specific

**Comment by medomohamed22** [comment]
I meant that there was a problem with the pi wallet in the QR code, but the problem was solved

**Comment by Opapai051148** [comment]
Thanks for news

Pada Sen, 3 Jun 2024 20.52, medomohamed22 ***@***.***>
menulis:

**Review by CryptoGing — APPROVED** [review]

**Pull request merged**
