### PR TITLE
PiOS License for PI SILK ROAD

### PR DESCRIPTION
**Pull request by Picloverteam**

### CODE REVIEW

**Comment by Picloverteam** [comment]
We rebuild the world together with Pi.

**Review by kokkalis — APPROVED** [review]

**Review by kokkalis — APPROVED** [review]

**Comment by Picloverteam** [comment]
Dear Sir, 

Thank you for your approved.
We will try our best to make complete the product and system soon. 

@Rita

**Comment by Khoerudinmumtaza** [comment]
Good

**Comment by Picloverteam** [comment]
| Silk Road for Pi | An E-commerce, multifunctional utility platform made by Vietnamese Pioneers. | Consumer Utility | .Net, C# | [SilkRoad](https://github.com/pi-apps/SilkRoad) | pi://brainstorm.pi/project/63ac0fe8781db4f06f97d9be | [demo](https://pisilkroad.com/) | (When available) |

Dear Sir, I want to upgrate this list.md again. I added on  brainstorm URL and change the Bussiness Tool become Consumer Utility.

Thank you.

**Pull request merged**
