### PR TITLE
add 2345Pi APP Nav

### PR DESCRIPTION
**Pull request by bailaoshijiadao**

### CODE REVIEW

**Comment by pi-core-team** [comment]
Hello @bailaoshijiadao the PiOS app list is intended for projects that are open source. Are you committed to providing your code open source?

**Comment by pi-core-team** [comment]
The repository has been created and your admin access has been assigned. Please make sure to move your code to this repository

**Review by pi-core-team — APPROVED** [review]

**Comment by tysseo7** [comment]
Information necessary for the PR to be approved:

*Category
Game

*Title
Pi Bingo (Testnet)

*I included the following in my code.

"Pi, Pi Network and the Pi logo are trademarks of the Pi Community Company."

*Description
This app is a game which user guesses a number from 1 to 10 that appears at random. To play this game user must  pay 1 Test Pi to Pi Pool. 

If user win, he/she receive 80% of Pi Pool.

This app is written by HTML and Javascript.

*Link to Pi Brainstorm project proposal (project name until feature is ready)
https://github.com/tysseo7/piBingoTestnet

**Comment by Ejinshuai** [comment]
PI Network🚀🚀🚀

**Pull request merged**
