### PR TITLE
Add Pi-Chicks app

### PR DESCRIPTION
**Pull request by piappart**

### CODE REVIEW

**Review by kokkalis — CHANGES_REQUESTED** [review]
The name of the app can be in the form of “App_Name for Pi”, “App_Name on Pi”, “App_Name”, but not in the form of “Pi App_Name” to avoid confusion with apps developed by the Pi Core Team. Is it ok to make this change?

**Comment by popyelove** [comment]
add pipet app

**Comment by popyelove** [comment]
add piapps

**Comment by CryptoGing** [comment]
The PiOS app list is for projects to provide their applications code as Open Source to the community. Will all the code for these applications be made open source?

**Comment by CryptoGing** [comment]
@popyelove @piappart are you looking to open source your projects?

**Comment by popyelove** [comment]
yes but not now. still some code need to be fixed and make adjustment. we will publish and submit code after that. thsan you so much



---Original---
From: ***@***.***&gt;
Date: Sat, Jan 14, 2023 02:29 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pi-apps/PiOS] Add Pi-Chicks app (PR #14)




 
@popyelove @piappart are you looking to open source your projects?

**Comment by CryptoGing** [comment]
Can you ping me here once the code is ready to be open sourced and we will add the applications to the list then

**Comment by popyelove** [comment]
definitely ok



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 18, 2023 03:39 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pi-apps/PiOS] Add Pi-Chicks app (PR #14)




 
Can you ping me here once the code is ready to be open sourced and we will add the applications to the list then

**Review by qux-8 — COMMENTED** [review]
Pretty much good

**Comment by pi-core-team** [comment]
To keep everything clean we want to move to one PR one Project. Can you please submit a new PR for each project individually so we can review them and get them accepted. 

@qux-8 
@popyelove 
@piappart 

Please make the updated request if you intend to Open Source your Code.

**Pull request closed without merging**
