### PR TITLE
add PiDAOMall to PiOS

### PR DESCRIPTION
**Pull request by Pi-MJun**

### CODE REVIEW

**Comment by CryptoGing** [comment]
The PiOS app list is to open source your application code and allow others to build upon it. Are you looking to make your application code public?

**Comment by Pi-MJun** [comment]
> The PiOS app list is to open source your application code and allow others to build upon it. Are you looking to make your application code public? 

Yes

**Comment by CryptoGing** [comment]
Okay, the name cannot be in the form PiDaoMall. The name can be in the form of “App_Name for Pi”, “App_Name on Pi”, or “App_Name”, but not in the form of “Pi App_Name” to avoid confusion with apps developed by the Pi Core Team.

Can you please update the name to a name you desire and meets the above constraints.

**Comment by Pi-MJun** [comment]
> > Okay, the name cannot be in the form PiDaoMall. The name can be in the form of “App_Name for Pi”, “App_Name on Pi”, or “App_Name”, but not in the form of “Pi App_Name” to avoid confusion with apps developed by the Pi Core Team.
> > 
> > Can you please update the name to a name you desire and meets the above constraints. 
> 
> Excuse me Can I change it to "DAO Mall for Pi"?
May I trouble you to help? Put
 “PiDAOMAll “Change to "DAO Mall for Pi"  Thanks a lot.
I can't operate it now.

**Review by Pi-MJun — COMMENTED** [review]
Thanks a lot.

**Review by CryptoGing — APPROVED** [review]

**Review by RamadanHash — COMMENTED** [review]
👍

**Pull request merged**
