### PR TITLE
Update list.md

### PR DESCRIPTION
**Pull request by BerkahLestariJambi**

### CODE REVIEW

**Review by Nusantaraproperty23 — APPROVED** [review]
Very good the aplication for pi ecosystem

**Review by Nusantaraproperty23 — APPROVED** [review]
This is a platform very good for pi ecosystem

**Review by Nusantaraproperty23 — APPROVED** [review]
Ok

**Review by Nusantaraproperty23 — APPROVED** [review]

**Comment by tate1650** [comment]
Hello! Since this PR seems to have been replaced by #230 I'm going to go ahead and close this one.

**Comment by BerkahLestariJambi** [comment]
Thanks

**Pull request closed without merging**
