### PR TITLE
314159U GCV MALL

### PR DESCRIPTION
**Pull request by 314159U**
314159U GCV MALL

### CODE REVIEW

**Comment by 314159U** [comment]
Dear official, I have resubmitted a new pull, please take the time to review it, thank you! @kokkalis

**Comment by CryptoGing** [comment]
This repositroy is for open source code, do you intend to open source your code?

You must remove all instances in which a speculative price for Pi is stated from this PR, the Brainstorm Proposal, and your application. This is against the Enclosed Mainnet rules and Pi Networks terms of service.

**Comment by 314159U** [comment]
> This repository is for open source code, do you intend to open source your code?
> 
> You must remove all instances in which a speculative price for Pi is stated from this PR, the Brainstorm Proposal, and your application. This is against the Enclosed Mainnet rules and Pi Networks terms of service.

Dear official, brainstorming proposal and pull have deleted the price statement. Thank you for your official reminder. Please review it again. Thank you!

**Comment by 314159U** [comment]
> This repository is for open source code, do you intend to open source your code?
>

**Comment by 314159U** [comment]
> This repository is for open source code, do you intend to open source your code?
> 
> You must remove all instances in which a speculative price for Pi is stated from this PR, the Brainstorm Proposal, and your application. This is against the Enclosed Mainnet rules and Pi Networks terms of service.

Yes, officially, we intend to open source access to PiOS.
Dear official, brainstorming proposal and pull have deleted the price statement. Thank you for your official reminder. Please review it again. Thank you!

**Comment by CryptoGing** [comment]
You must also remove all mentions of price within your application and you must allow Pioneers and Merchants to decide the price of their pi.

**Comment by 314159U** [comment]
> You must also remove all mentions of price within your application and you must allow Pioneers and Merchants to decide the price of their pi.

Dear officials, the content about the price has been deleted. If the name 314159U GCV MALL involves the price, please allow us to explain: the mall is only to provide a platform for some merchants who are willing to take actions for their own ideas, so as to facilitate merchants to sell goods or services to obtain Pi. The price of goods is defined by merchants themselves, and the purchase of goods is also freely chosen by pioneers, our mall only provides a platform without any other restrictions. The name is also to highlight the ideas of merchants, and there is no mandatory meaning attached. The mall is also to give pioneers more choices, for Pi Diversification and established, thank you!

**Pull request closed without merging**
