### PR TITLE
Update pi-commerce.md

### PR DESCRIPTION
**Pull request by Global-System-Indonesia**
"Toko Emas Berlian Harisa" is now preparing to build an ecosystem in the Pi Network community

### CODE REVIEW

**Comment by CryptoGing** [comment]
@Global-System-Indonesia This table is meant for teams that are submitting applications that meet the requirements of the Commerce hackathon that is ongoing currently. Your app doesn't seem to meet the criteria. 

I left comments on your other Pull Request about adding your applications to the PiOS list. We can add them however I need to know which apps are being open sourced so I can create repositories.

**Comment by CryptoGing** [comment]
We accepted this app into the PiOS list of applications and not the Commerce Hackathon

**Comment by Global-System-Indonesia** [comment]
We have actually built a Pi-Commerce ecosystem on our platform.
Are there any instructions and direction so that we enter this criterion.

**Comment by yassunar1** [comment]
Why...

**Comment by Dzen27bdg** [comment]
What happen, kok bisa...?

**Comment by CryptoGing** [comment]
The commerce hackathon was focused on building an application that used a map to connect Pioneers to stores that accept Pi. Upon reviewing your application we found that it was more focused on connecting Pioneers to sell Gold and jewelry rather than connect pioneers to stores.

**Comment by Global-System-Indonesia** [comment]
Please see our application that we changed since last February.

In accordance with the direction of Coreteam, the Harisa Jewelery application is developing not only the focus of gold sales, but now many things.

Especially since February, we actually focus on making applications in terms of ecosystems, more than 100 pioneers have been incorporated in our ecosystems and are ready to accept Pi Network as a medium of exchange.

**Comment by Opapai051148** [comment]
Thanks for news and thanks to Pi Network as a medium of exchange.

**Comment by Global-System-Indonesia** [comment]
We will be ready to run the ecosystem starting March 14 2024

**Pull request closed without merging**
