### PR TITLE
Update list.md

### PR DESCRIPTION
**Pull request by Asicro0507**
My app is a marketplace that many people can sell or buy source code, game, music, software, ebook, gift card.... Everyone can earn more pi by selling or reffering people to buy items in Moon Digital Marketplace. Please check my website is at https://pimoon.io.

### CODE REVIEW

**Comment by pi-core-team** [comment]
Hello, thank you for your interest in joining the PiOS list. This list is intended for applications that will open source their applciations code. If accepted will you open source your code?

**Comment by Asicro0507** [comment]
I will open source my Moon Digital Marketplace code and look forward to the support from Pi Core Team.

**Review by Sahnesiguzel33 — APPROVED** [review]

**Comment by Opapai051148** [comment]
Thanks for email.

Pada tanggal Sen, 19 Jun 2023 09.38, Sahnesiguzel33 <
***@***.***> menulis:

**Comment by CryptoGing** [comment]
Closing this request due to lack of response

**Pull request closed without merging**
