### PR TITLE
Update list.md

### PR DESCRIPTION
**Pull request by Global-System-Indonesia**
My Project use PHP, many project will develop with my sdk.

Project List:
PT. GOLDEN DIAMOND HARISA (GDH-PiJEWELLERY), https://testnet.harisajewellery.com

### CODE REVIEW

**Comment by Opapai051148** [comment]
Good  news.go..go...with the project.don't give up!

**Comment by Opapai051148** [comment]
Good news.Let us know more/ about the project

**Comment by Ketouth** [comment]
I think this is a good app to support ecosystem in Pi Network.

**Comment by Opapai051148** [comment]
Thank for info.

Pada tanggal Sab, 1 Jul 2023 19.30, Ketouth ***@***.***>
menulis:

**Review by Opapai051148 — APPROVED** [review]
Unsubscribe

**Comment by yassunar1** [comment]
sukses selalu pak..mantaap..

**Comment by CryptoGing** [comment]
@Global-System-Indonesia This is list is intended for projects that want to open source their project. Are you looking to release the code for the applications?

**Comment by Global-System-Indonesia** [comment]
> @Global-System-Indonesia This is list is intended for projects that want to open source their project. Are you looking to release the code for the applications?

Yes, Definitely, we are ready to share our sources

**Comment by Dzen27bdg** [comment]
semoga semakin berkembang dan sukses selalu...

**Comment by CryptoGing** [comment]
Do you need individual repositories for each project?

**Comment by CryptoGing** [comment]
@Global-System-Indonesia did you intend to delete this Pull Request? I reviewed your changes and the list.md file is now deleted which I can't accept this PR as it will delete the list.md file.

**Pull request closed without merging**
